spring:
  application:
    name: register
server:
  port: 7070

eureka:
  environment: dev
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7070/eureka/
  server:
    enable-self-preservation: false

info:
  app:
    name: register-center
    description: 注册中心
