spring:
  application:
    name: base
  datasource:
    url: jdbc:mysql://192.168.2.110/info?useUnicode=true&characterEncoding=utf-8
    username: xuelei
    password: xuelei
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

server:
  port: 9000

info:
  app:
    name: base service
    description: base服务


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/
