spring:
  application:
    name: gateway

server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka
zuul:
  routes:
    api:
      path: /api/**
      serviceId: base


