spring:
  application:
    name: gateway

server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka
zuul:
  routes:
    base:
      path: /base/**
      serviceId: base
    ram:
      path: /ram/**
      serviceId: ram

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1


